wso2-extensions/identity-outbound-auth-facebook

components/org.wso2.carbon.identity.application.authenticator.facebook/pom.xml
features/org.wso2.carbon.identity.application.authenticator.facebook.server.feature/pom.xml
pom.xml

Merge Release 5.1.1 to master

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorConstants.java

Fixed the IDP side subject mapping

Fixed subject claim uri in IDP

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookProcessResponseTests.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/TestAuthnContextWithoutMocking.java

- Fix class level ClaimConfig object issue

Fix class level ClaimConfig object issue

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java

- Handling null pointer issue when extracting authentication context state.
- Immediate
- N/A

Handling null pointer issue when extracting authentication context state.

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java

Add configuration properties required for REST APIs

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java

Fixes https://github.com/wso2/product-is/issues/7983

Update isConfidential field in client secret

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java

Resolves part of wso2/product-is#8049

Add missing properties to facebook authenticator

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java

Fixes https://github.com/wso2/product-is/issues/11833

Add diagnostic logs

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java

Reverts wso2-extensions/identity-outbound-auth-facebook#40

Revert "Add diagnostic logs"

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorTests.java

Reverts wso2-extensions/identity-outbound-auth-facebook#44

Revert "Change JIT provisioned Managed profile name"

---

components/org.wso2.carbon.identity.application.authenticator.facebook/pom.xml
features/org.wso2.carbon.identity.application.authenticator.facebook.server.feature/pom.xml
pom.xml

change version to 5.1.24-SNAPSHOT

---

components/org.wso2.carbon.identity.application.authenticator.facebook/pom.xml
features/org.wso2.carbon.identity.application.authenticator.facebook.server.feature/pom.xml
pom.xml

Bump POM versions to major version: 6.0.0 for IPK product

Bump pom version to major version

---

components/org.wso2.carbon.identity.application.authenticator.facebook/pom.xml
pom.xml

Remove carbon.ui dependency

---

features/org.wso2.carbon.identity.application.authenticator.facebook.server.feature/pom.xml
pom.xml

Update carbon-identity-framework version range

---

components/org.wso2.carbon.identity.application.authenticator.facebook/pom.xml
components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorTests.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookProcessResponseTests.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/TestAuthnContextWithoutMocking.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/TestUtils.java
pom.xml

* Add diagnostic logs for the FB authenticator

Add diagnostic logs for the authenticator

---

pom.xml

$Subject
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/154
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/156

Bump OIDC Authenticator Version

---

components/org.wso2.carbon.identity.application.authenticator.facebook/pom.xml
components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorTests.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/TestConstants.java
pom.xml

$Subject
- https://github.com/wso2/product-is/issues/15684

Modify Facebook Authenticator to Support Native SDK based Federation Flow in API Based Authentication

---

pom.xml

Bump Framework and OIDC Authenticator Versions

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/test/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorTests.java

$Subject
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/160

Modify Callback URL for API based Authentication.

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticatorConstants.java
pom.xml

Related to https://github.com/wso2/product-is/issues/15684

Change state value for api based auth

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java

note $subject
- https://github.com/wso2-extensions/identity-outbound-auth-facebook/pull/62
- https://github.com/wso2/product-is/issues/20336
- https://github.com/wso2/product-is/issues/20348

Removing unwanted comments

---

.github/workflows/pr-builder.yml
codecov.yml
components/org.wso2.carbon.identity.application.authenticator.facebook/pom.xml
features/org.wso2.carbon.identity.application.authenticator.facebook.server.feature/pom.xml
pom.xml

This PR adds Codecov and JaCoCo configurations to the repository.

[Automated PR]Add Codecov and JaCoCo configurations

---

components/org.wso2.carbon.identity.application.authenticator.facebook/src/main/java/org/wso2/carbon/identity/application/authenticator/facebook/FacebookAuthenticator.java

- $Subject
- https://github.com/wso2-extensions/identity-outbound-auth-facebook/pull/54

Add a New Line in `isAPIBasedAuthenticationSupported()` Method
